### PR TITLE
Add Contributor bot 

### LINKED ISSUE #33: Add an all contributors bot to the project
Check this repo https://github.com/fishonamos/art-peace 

That's how we want to do it.

### PR DESCRIPTION
**Pull request by Solomonsolomonsolomon**
all contributors

closes #33

### CODE REVIEW

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @fishonamos  for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @fishonamos  for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @fishonamos  for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @Solomonsolomonsolomon  for code

**Comment by Solomonsolomonsolomon** [comment]
@fishonamos  awaiting you

**Comment by fishonamos** [comment]
@all-contributors  add @rajiabdul , and @GoSTEAN as contributors for Code.

**Comment by fishonamos** [comment]
https://github.com/all-contributors please add @rajiabdul  for code

**Comment by fishonamos** [comment]
@all-contributors please add @GoSTEAN for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @manlikeHB for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @Akshola00 for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @SoarinSkySagar for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @saimeunt for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @Eche5 for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contrubutors please add @PoulavBhowmick03  for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @PoulavBhowmick03 for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @No-bodyq for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors  please add @Villarley for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @Otaiki1 for code

**Comment by Solomonsolomonsolomon** [comment]
@all-contributors please add @fishonamos for review

**Pull request merged**
