### PR TITLE
fix: register land modal and typescript config

### PR DESCRIPTION
**Pull request by MarcusDavidG**
- Fixed import paths in RegisterLandModal.tsx
- Fixed TypeScript configuration in tsconfig.json
- Removed package-lock.json in favor of pnpm
- Added proper type annotations

## Detailed Information

---

## Related Issues

Closes #251

---

## Type of Change

- [x] 🐛 Bug fix or ⚙️ enhancement
- [x] ✨ New feature or Chore (change with no new features or fixes)
- [x] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [x] The code follows the style guidelines of this project.
- [x] All new and existing tests pass.
- [x] This pull request is ready to be merged and reviewed.

### CODE REVIEW

**Comment by Solomonsolomonsolomon** [comment]
please add issue number

**Comment by MarcusDavidG** [comment]
Done!

**Comment by Solomonsolomonsolomon** [comment]
i dont see the map picker, can you include relevant screenshots

**Comment by MarcusDavidG** [comment]
Screenshot from 2024-12-26 17-09-42

**Comment by MarcusDavidG** [comment]
Map Piclker(longitude and latitude)

**Comment by Solomonsolomonsolomon** [comment]
This doesn't align with the issue, the issue was to replace the latitude and longitude fields with a map picker, so users pick their location from a map , not entering the lat and lon manually

**Review by Solomonsolomonsolomon — COMMENTED** [review]
please re-read issue #240  again as this doesn't tally with the issue

**Pull request closed without merging**
