### PR TITLE
test: add test for buy_land function

### PR DESCRIPTION
**Pull request by martinvibes**
## Detailed Information
add tests for buy_land function
---

## Related Issues

Closes #<issue-number>

---

## Type of Change

- [ ] 🐛 Bug fix or ⚙️ enhancement
- [x] ✨ New feature or Chore (change with no new features or fixes)
- [ ] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [x] The code follows the style guidelines of this project.
- [x] All new and existing tests pass.
- [x] This pull request is ready to be merged and reviewed.

### CODE REVIEW

**Comment by fishonamos** [comment]
Will close and reopen for odhack

**Comment by martinvibes** [comment]
hey @fishonamos i'm done with the test and evrything is passing

**Comment by fishonamos** [comment]
Update your pr, resolve conflicts.

**Comment by martinvibes** [comment]
creating a pr very soon

**Pull request closed without merging**
