### PR TITLE
[test #83] integration tests for Land and NFT contracts

### LINKED ISSUE #83: Integration Tests for Land Registry and NFT Interaction
Task: Create integration tests to ensure proper interaction between the LandRegistry and LandNFT contracts.

Definition of Done:
•  Tests cover the full flow from land registration to NFT minting and transfer.
•  Edge cases in cross-contract interactions are identified and tested.
- Update logic if necessary. 

Note: Only applications through the OnlyDust platform will be considered.

### PR DESCRIPTION
**Pull request by jorgezerpa**
## Detailed Information
This changes has the integration tests for the interaction between LandRegistry contract and the NFT contract. 
During the tests implementation, I found an error related with the transfer_land and approve_land functions. The LandRegistry contract address that was registered on the NFT contract did not matched with the real address. This is because of a circular parameters error, in more detail:
- To deploy the NFT contract we need the address of the LandRegistry contract. 
- To deploy the LandRegistry contract we need the address of the NFT contract.
<br>
To fix this, I changed the params of the constructor of LandRegistry, to receive the classHash of the NFT contract (instead of the contract address) and deploy the NFT contract from the constructor of LandRegistry using a deploy syscall ([ref about syscalls here](https://book.cairo-lang.org/appendix-08-system-calls.html)). By this way, both contracts has the corresponding contract_address of each other.
<br><br>
pd: because of these changes, I had to modify too, the deploy function on the test_land_register.cairo file, to adapt to the new params sended to the constructor. By last, I enabled the asserts in NFT contract methods (was commented) that verifies that the calls comes only from the LandRegistry contract.

---
### Closes #83
---

## Type of Change

- [x] 🐛 Bug fix or ⚙️ enhancement
- [x] ✨ New feature or Chore (change with no new features or fixes)
- [ ] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [x] The code follows the style guidelines of this project.
- [x] All new and existing tests pass.
- [x] This pull request is ready to be merged and reviewed.

### CODE REVIEW

**Comment by jorgezerpa** [comment]
Sorry, I do not download the last changes made yesterday, I`ll fix the conflicts and push again 🏃

**Comment by fishonamos** [comment]
Hi @jorgezerpa . Nice! Please fix the conflicts!

**Comment by fishonamos** [comment]
LGTM!

**Comment by fishonamos** [comment]
Thank you for the pr @jorgezerpa !

**Comment by jorgezerpa** [comment]
@fishonamos Thanks to you! I look forward to keep contributing🚀

**Pull request merged**
