### PR TITLE
feat: land register for pay fee

### LINKED ISSUE #129: Establish a Fee Structure for Land Registration
Define and implement a standard fee structure for land registration. This fee will be calculated based on area of the land.

### PR DESCRIPTION
**Pull request by GoSTEAN**
## Related Issues

Closes #129

### CODE REVIEW

**Comment by fishonamos** [comment]
Now, you need to update the any related fns like registerland, create landid, integration tests etc.

This is means you need to update the deploy function and set an initial fee.

**Comment by fishonamos** [comment]
Also update the pr title correctly

**Comment by GoSTEAN** [comment]
> Now, you need to update related functions like registerland, create landid, integration tests etc.
> 
> This is means you need to update the deploy function and set an initial fee. 

Updating the deploy function in which of the tests?
So basically you're saying I should Update all the tests?

**Comment by fishonamos** [comment]
> > Now, you need to update related functions like registerland, create landid, integration tests etc.
> > This is means you need to update the deploy function and set an initial fee.
> 
> Updating the deploy function in which of the tests? So basically you're saying I should Update all the tests?

You need to innialialise the fee variable with an innitial value. Check tests that may be affected and update them. You need to also check that fee is paid before land is registered.

**Comment by fishonamos** [comment]
Fee is only paid for registration.

**Comment by fishonamos** [comment]
We fixed the tests as this is urgently needed. Thank you for your contribution!👏🏽

Merging

**Pull request merged**
