### PR TITLE
Feat 174 connect UI with contract

### PR DESCRIPTION
**Pull request by jorgezerpa**
##### Issue #174

Hello!! This is just to show the progress of the task and to request feedback about some problems I found (I let them down). Still not ready for merge.

### This PR has:
- All logic for login with wallet is ready, and corner cases like refresh and keeps logged in, re-request access when wallets logout after X time, etc. are managed. 
- The UI of all views is builded (Some of them still has mock data). 
- To interact easily with contracts, I create a hook "useLandverContract" that return a ready to use contract instance, that allows to read-write contract. 

### I found some problems:
- The create functionality is failing due to the registration fee conditionals, we should wait for that issue to be fixed to fully test it. 
- Any function that requieres the land_id as parameter, is failing because of such id is a too big number, so JS cannot handle correctly. I tried to send it like a string but gives me error that expects a number. And when I send it as a bigInt it fails because it modifies the value. I know it should be a way because in Voyager if you send it, it works perfectly! but I don't find the way to make it work here. 
- The data returned from contract does not match the desing. For example, the statuses of the land in design are different from the ones return from the contract. By know, I worked with what the contract returns. 

## Type of Change

- [ ] 🐛 Bug fix or ⚙️ enhancement
- [x] ✨ New feature or Chore (change with no new features or fixes)
- [ ] 📚 Documentation update

---

## Checklist (select as many as applicable)

- [x] The code follows the style guidelines of this project.
- [ ] This pull request is ready to be merged and reviewed.

### CODE REVIEW

**Comment by Solomonsolomonsolomon** [comment]
@jorgezerpa Nice work! Please proceed accordingly. The issue with the land ID has been noted and is undergoing modifications. However, I noticed a few problems:
1. You have typed multiple items as any. While this works during development, it will cause build issues as we do not allow explicit use of any. Please create a types folder and define types appropriately.
2. I also noticed that you upgraded the Next.js version from 14.2.15 to 15.0.3. Was there a specific reason for this? If not, kindly revert these changes.
Thank you, and once again, great work!

**Comment by fishonamos** [comment]
Nice progress @jorgezerpa.

**Comment by jorgezerpa** [comment]
👨‍🚀GN!!
All designed views are builded. Almost all the views has its functionality except for the points mentioned below. 

### What is left:
- In Dashboard logged as owner -> In the best seller section, I fetch the LandSold event to get the data for the table. But I could not test it because I can not buy a land due to errors on the buy_land function. If I call from owner address I get the error "Cannot buy own listing" and if I call from another address I get "Only Owner can transfer". By now mock data is showed. But I let it ready just to uncomment the real state when the problem is fixed. 
- Collections-detail logged as ownner -> There is no way to get the data for the land transaction history. There is a land_transaction_history function, but just returns an array of ids so it is missing data showed in the designed table. 
- Inspector views -> the UIs are developed. Not show real data because I dont have from where to get the data for the view. For example: In dashboard, things like Registration Request, verified lands...
- The create and update land logic is already implemented. Just wating for test when the land ids issue get fixed. 
- **(Sugestion)**: Add timestamp to all events so we can show the date on the list. 

Aside that, I think adding keys to the events could solve most of the missing points, because it will make possible query for events more specifically. For example, request for approved lands by an specific inspector, etc. 

Please test and let me know what are the priorities or what is missing aside the mentioned points above. I'm attentive😀

**Comment by Solomonsolomonsolomon** [comment]
LGTM

**Pull request merged**
