### PR TITLE
feat: setup apibara indexer to track land registry events

### LINKED ISSUE #166: Setup apibara indexer to track land registry events
Check the https://www.apibara.com/docs

Track the landregistry events. Setup with postgres.

This is a blocking issue. #183 depends on it.

### PR DESCRIPTION
**Pull request by ooochoche**
## Detailed Information

Successfully setup apibara indexer

## Related Issues

Closes #166

### CODE REVIEW

**Comment by fishonamos** [comment]
LandRegistered: LandRegistered,
        LandTransferred: LandTransferred,
        LandVerified: LandVerified,
        LandUpdated: LandUpdated,
        LandInspectorSet: LandInspectorSet,
        InspectorAdded: InspectorAdded,
        InspectorRemoved: InspectorRemoved,
        FeeUpdated: FeeUpdated,
        ListingCreated: ListingCreated,
        ListingCancelled: ListingCancelled,
        ListingPriceUpdated: ListingPriceUpdated,
        LandSold: LandSold,

**Comment by ooochoche** [comment]
> ```
>     LandRegistered: LandRegistered,
>     LandTransferred: LandTransferred,
>     LandVerified: LandVerified,
>     LandUpdated: LandUpdated,
>     LandInspectorSet: LandInspectorSet,
>     InspectorAdded: InspectorAdded,
>     InspectorRemoved: InspectorRemoved,
>     ListingCreated: ListingCreated,
>     ListingCancelled: ListingCancelled,
>     ListingPriceUpdated: ListingPriceUpdated,
>     LandSold: LandSold,
> ```

Can you give me more info about this?

**Comment by fishonamos** [comment]
Please update the pr to track all the events. Use starknet sepolia not Ethereum please.

**Comment by fishonamos** [comment]
> > ```
> >     LandRegistered: LandRegistered,
> >     LandTransferred: LandTransferred,
> >     LandVerified: LandVerified,
> >     LandUpdated: LandUpdated,
> >     LandInspectorSet: LandInspectorSet,
> >     InspectorAdded: InspectorAdded,
> >     InspectorRemoved: InspectorRemoved,
> >     ListingCreated: ListingCreated,
> >     ListingCancelled: ListingCancelled,
> >     ListingPriceUpdated: ListingPriceUpdated,
> >     LandSold: LandSold,
> > ```
> 
> Can you give me more info about this?

Those are the events.

**Comment by fishonamos** [comment]
This is our contract address: 0x5a4054a1b1389dcd48b650637977280d32f1ad8b3027bc6c7eb606bf7e28bf5

**Comment by fishonamos** [comment]
Check here to see sample of the event emitted: https://sepolia.starkscan.co/contract/0x05a4054a1b1389dcd48b650637977280d32f1ad8b3027bc6c7eb606bf7e28bf5#events

**Pull request merged**
